import React from "react";
import {createContext, ProducerProps, Sources} from "async-states";
import {useAsyncState} from "react-async-states";
import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '../styles/Home.module.css'
import {myBackendContext} from "./becontext";

const inter = Inter({subsets: ['latin']})

async function fetchUsers(props: ProducerProps<any>) {
  let controller = new AbortController();
  props.onAbort(controller.abort.bind(controller));
  let signal = controller.signal;

  const response = await fetch(`https://jsonplaceholder.typicode.com/users`, {signal});
  if (!response.ok) {
    throw new Error(`${response.status}`);
  }

  return response.json();
}

let users = Sources.for("users", fetchUsers, {context: myBackendContext});

export async function loader() {
  return users.runp();
}

export default async function Home() {
  await users.runp();
  let {state} = useAsyncState(users);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <h2>Users page:</h2>
        <ul>
          {state.status === "success" && state.data.map((user: any) => (
            <li key={user.id}>
              <a href={`/users/${user.id}`}>
                {user.username}
              </a>
            </li>
          ))}
        </ul>
      </main>
    </>
  )
}
